### ISSUE TITLE
ITV player error

### ISSUE THREAD

**Issue by jerheij** [blissland/blissflixx#36]
When I try to play something through ITV I get this error after waiting a couple of minutes:

> Traceback (most recent call last):
  File "blissflixx.py", line 95, in default
    ret = call(**datadict)
  File "/etc/blissflixx/lib/api/playr.py", line 19, in play
    cmd = extractor.itv.extract(url)
  File "/etc/blissflixx/lib/extractor/itv.py", line 33, in extract
    page = get(url)
  File "/etc/blissflixx/lib/extractor/itv.py", line 14, in get
    r = requests.get(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.itv.com', port=443): Max retries exceeded with url: /hub/coronation-street/1a0694a9219 (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)'),))

Is there a way to disable verify of certificates?

**Comment by blissland** [comment]
See this thread for possible solutions:

https://stackoverflow.com/questions/31649390/python-requests-ssl-handshake-failure

**Comment by jerheij** [comment]
I've tried installing the packages from that link but it didn't solve it, now I get a "process exit 3" error instead.

**Comment by diegorodriguezv** [comment]
Hello @jerheij. I hope this issue has been solved by updating blissflixx and your pi. I´m going to close this as there is not much information available to reproduce the problem or fix it. If you run into any more trouble, feel free to open a new issue and I'll help.
