### ISSUE TITLE
Twitch channel prevents blissflixx from starting

### ISSUE THREAD

**Issue by diegorodriguezv** [blissland/blissflixx#64]
Twitch deprecated their kraken API and now blissflixx won't start.
```
pi@rpitest:~/src/blissflixx $ ./blissflixx.py --port 80
[07/Mar/2020:10:01:33]  BLISSFLIXX Starting...
Traceback (most recent call last):
  File "./blissflixx.py", line 47, in <module>
    import api, pwd, grp
  File "/home/pi/src/blissflixx/lib/api/__init__.py", line 1, in <module>
    import channels
  File "/home/pi/src/blissflixx/lib/api/channels.py", line 162, in <module>
    installed = InstalledChannels()
  File "/home/pi/src/blissflixx/lib/api/channels.py", line 81, in __init__
    self._refresh()
  File "/home/pi/src/blissflixx/lib/api/channels.py", line 103, in _refresh
    channels.append(Channel(p, False))
  File "/home/pi/src/blissflixx/lib/api/channels.py", line 27, in __init__
    feeds = module.feedlist()
  File "/home/pi/src/blissflixx/chls/bfch_twitch/__init__.py", line 19, in feedlist
    return map(lambda x: {'title': x['game']['name'], 'name': quote_plus(x['game']['name'].encode('utf-8'))}, get_json(_FEEDLIST_URL)['top'])
  File "/home/pi/src/blissflixx/lib/chanutils/chanutils.py", line 77, in get_json
    r = get(url, params=params, **kwargs)
  File "/home/pi/src/blissflixx/lib/chanutils/chanutils.py", line 44, in get
    raise Exception("Request : '" + url + "' returned: " + str(r.status_code))
Exception: Request : 'https://api.twitch.tv/kraken/games/top?limit=50' returned: 41
```

Error 410 Gone: Indicates that the resource requested is no longer available and will not be available again.

**Comment by diegorodriguezv** [comment]
If you are experiencing this problem try:
```
git pull
git clean -f -d
```
